# Version 1.0.0
# Similar config between jobs
common: 
  - &defaults
    working_directory: /go/src/github.com/Static-Void-Academy/circleci-hello
    docker:
      - image: circleci/golang:1.11.1-stretch

  - &get_deps
      run: go get -d ./...

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *get_deps
      - run:
          name: Build the executable
          command: |
            go build
            echo "Blah blah hello"
      - persist_to_workspace:
          root: .
          paths: ./*
      - store_artifacts:
          path: ./circleci-hello

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - *get_deps
      - run: go test

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build

